version: "3.8"

services:
  bitbucket-dc-mcp:
    # Use locally built image (build first with: docker build -t bitbucket-dc-mcp:latest .)
    image: bitbucket-dc-mcp:latest

    # Build configuration (alternative to pre-built image)
    build:
      context: .
      dockerfile: Dockerfile

    # Container name for easy reference
    container_name: bitbucket-dc-mcp-server

    # Environment variables for MCP server configuration
    environment:
      # Required: Your Bitbucket Data Center URL
      BITBUCKET_URL: ${BITBUCKET_URL:-https://bitbucket.example.com}

      # Authentication method: pat, basic, oauth1, or oauth2
      BITBUCKET_AUTH_METHOD: ${BITBUCKET_AUTH_METHOD:-pat}

      # Personal Access Token (required if using PAT auth)
      BITBUCKET_TOKEN: ${BITBUCKET_TOKEN}

      # Basic auth credentials (required if using Basic auth)
      # BITBUCKET_USERNAME: ${BITBUCKET_USERNAME}
      # BITBUCKET_PASSWORD: ${BITBUCKET_PASSWORD}

      # Optional: Logging level (debug, info, warn, error)
      LOG_LEVEL: ${LOG_LEVEL:-info}

      # Optional: Rate limit (requests per minute)
      BITBUCKET_RATE_LIMIT: ${BITBUCKET_RATE_LIMIT:-100}

      # Optional: Request timeout in milliseconds
      BITBUCKET_TIMEOUT_MS: ${BITBUCKET_TIMEOUT_MS:-30000}

      # Optional: Pretty print logs (true/false)
      LOG_PRETTY: ${LOG_PRETTY:-false}

    # Volume mount for persistent configuration
    # Uncomment to use config file instead of environment variables
    # volumes:
    #   - ~/.bitbucket-dc-mcp:/root/.bitbucket-dc-mcp

    # Enable stdin for stdio communication (required for MCP protocol)
    stdin_open: true

    # Disable tty to avoid terminal issues with stdio
    tty: false

    # Restart policy
    restart: unless-stopped

    # Health check configuration (inherits from Dockerfile)
    # Checks every 30s if server is running
    healthcheck:
      test: ["CMD", "node", "/app/dist/healthcheck.js"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

    # Resource limits (optional but recommended)
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
        reservations:
          cpus: "0.25"
          memory: 512M
# Example usage:
# 1. Build the image:
#    docker-compose build
#
# 2. Start the server:
#    docker-compose up -d
#
# 3. View logs:
#    docker-compose logs -f bitbucket-dc-mcp
#
# 4. Check health:
#    docker-compose ps
#
# 5. Stop the server:
#    docker-compose down
#
# 6. Test MCP protocol:
#    echo '{"jsonrpc":"2.0","method":"initialize","params":{},"id":1}' | docker-compose exec -T bitbucket-dc-mcp cat
