name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [22.14.0]

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Check TypeScript
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Run benchmark tests
        # Quality gate ensuring semantic search relevance thresholds stay above 85%
        run: npm run test:benchmark
